export EDITOR=vim
alias ls='ls --color=auto'
alias ll='ls -l'
alias p='ping google.com'
alias pull='git pull origin master'
alias push='git push origin master'
alias wget='wget -c'
alias wgets='wget -c --no-check-certificate'
alias bc='python'
alias rm='rm -i'
alias netstat='sudo netstat -lptu'
alias pss='pss -i'
